all: up

up:
	@sudo docker compose ./srcs/docker-compose.yml up

down:
	@sudo docker compose ./srcs/docker-compose.yml down

stop:
	@sudo docker compose ./srcs/docker-compose.yml stop

start:
	@sudo docker compose ./srcs/docker-compose.yml start

status :
	@sudo docker ps
