version: '3.5'

networks:
  network:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - network
    restart: unless-stopped
  php:
    container_name: php
    build: ./requirements/php
    networks:
      - network
    restart: unless-stopped
