version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: unless-stopped
