version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
#  wordpress:
#    container_name: wordpress
#    build: ./requirements/wordpress
#  maria-db:
#    container_name: maria-db
#    build: ./requirements/maria-db
