# Docker Compose
version: '3.5'

# Networks
networks:
  inception:

# Services
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
